### ISSUE TITLE
Change USF Bull Runner URL in GTFS data

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/bullrunner-gtfs-realtime-generator#6]
I noticed this when clicking on the "USF Bull Runner" link in the current OneBusAway staging server:
http://app.staging.obahart.org/where/standard/#m(route)route(USF%20BullRunner_C)

Apparently the main USF PATS website changed, since you now see this message before being redirected:

>The USF Parking & Transportation Services Department has a brand new Website. You will be redirected to usf.edu/parking in 5 seconds.

The new URL in GTFS agency.txt should be http://usf.edu/parking

@jmfield2 Could you please change this?

**Comment by jmfield2** [comment]
Should this be 
http://usf.edu/parking
or
http://www.usf.edu/administrative-services/parking/
?

The former gives a 302 redirect to the latter:

Request URL:http://www.usf.edu/parking
Request Method:GET
Status Code:301 Moved Permanently

Date:Fri, 16 Jan 2015 02:43:14 GMT
Location:http://www.usf.edu/administrative-services/parking

So, I'm assuming it is better to use the latter in case the redirect is removed at some point in the future.

**Comment by barbeau** [comment]
Yeah, good point, let's use the latter.

**Comment by jmfield2** [comment]
Fixed a0df7c437fcd59928f71f10bba5491ab6e5fc00e

**Comment by barbeau** [comment]
Thanks @jmfield2!
